// Merges data/work.json + lab/_meta/*.json into data/projects.js (a plain script, so the
// homepage works from file:// and GitHub Pages with no fetch). Also counts the real
// Playwright tests in each lab page's spec so the "tests passing" badges never lie.
import { readFile, readdir, writeFile, access } from 'node:fs/promises';

const exists = (p) => access(p).then(() => true, () => false);
const countTests = (src) => (src.match(/\btest\(\s*['"`]/g) || []).length;

const work = JSON.parse(await readFile('data/work.json', 'utf8'));

const metaFiles = (await readdir('lab/_meta')).filter((f) => f.endsWith('.json')).sort();
const lab = [];
for (const f of metaFiles) {
  const m = JSON.parse(await readFile(`lab/_meta/${f}`, 'utf8'));
  // Fail loudly on incomplete metadata rather than shipping broken links.
  const missing = ['id', 'slug', 'file', 'title', 'category', 'description', 'prompt'].filter((k) => !m[k]);
  if (!m.qa?.methodology?.length || !m.qa?.playwright) missing.push('qa');
  if (missing.length) throw new Error(`lab/_meta/${f} is missing: ${missing.join(', ')}`);
  if (!(await exists(m.file))) throw new Error(`lab/_meta/${f}: ${m.file} does not exist`);
  const spec = `tests/lab/${m.slug}.spec.ts`;
  const tests = (await exists(spec)) ? countTests(await readFile(spec, 'utf8')) : 0;
  const thumb = `lab/thumbs/${m.id}.jpg`;
  lab.push({
    ...m,
    kind: 'lab',
    spec: (await exists(spec)) ? spec : null,
    tests,
    thumb: (await exists(thumb)) ? thumb : null,
  });
}

const projects = [...lab];
for (const w of work) {
  projects.push({
    ...w,
    kind: w.category === 'Client Work' ? 'client' : 'classic',
    thumb: w.thumb && (await exists(w.thumb)) ? w.thumb : null,
  });
}

const header = '// Generated by scripts/build-data.mjs; edit data/work.json or lab/_meta/*.json instead.\n';
await writeFile('data/projects.js', `${header}window.PROJECTS = ${JSON.stringify(projects, null, 2)};\n`);

const total = lab.reduce((n, p) => n + p.tests, 0);
console.log(`Wrote ${projects.length} projects (${lab.length} lab pages, ${total} lab tests).`);
