// Merges data/work.json + lab/_meta/*.json into data/projects.js (a plain script, so the
// homepage works from file:// and GitHub Pages with no fetch). Also counts the real
// Playwright tests in each lab page's spec so the "tests passing" badges never lie.
import { readFile, readdir, writeFile, access } from 'node:fs/promises';

const exists = (p) => access(p).then(() => true, () => false);
// Only count `test(` that starts a statement: specs can assert on generated code containing "test('…'" strings.
const countTests = (src) => (src.match(/^\s*test\(\s*['"`]/gm) || []).length;
// Every conditional skip in this repo is `test.skip(isMobile, ...)`: it skips on exactly one of the two projects.
const countSkips = (src) => (src.match(/\btest\.skip\(\s*isMobile\b/g) || []).length;
const PROJECTS_PER_RUN = 2; // desktop + mobile (playwright.config.ts)

const work = JSON.parse(await readFile('data/work.json', 'utf8'));

const metaFiles = (await readdir('lab/_meta')).filter((f) => f.endsWith('.json')).sort();
const lab = [];
for (const f of metaFiles) {
  const m = JSON.parse(await readFile(`lab/_meta/${f}`, 'utf8'));
  // Fail loudly on incomplete metadata rather than shipping broken links.
  const missing = ['id', 'slug', 'file', 'title', 'category', 'description', 'prompt'].filter((k) => !m[k]);
  if (!m.qa?.methodology?.length || !m.qa?.playwright) missing.push('qa');
  if (missing.length) throw new Error(`lab/_meta/${f} is missing: ${missing.join(', ')}`);
  if (!(await exists(m.file))) throw new Error(`lab/_meta/${f}: ${m.file} does not exist`);
  const spec = `tests/lab/${m.slug}.spec.ts`;
  const specSrc = (await exists(spec)) ? await readFile(spec, 'utf8') : '';
  const tests = countTests(specSrc);
  const skips = countSkips(specSrc);
  const thumb = `lab/thumbs/${m.id}.jpg`;
  lab.push({
    ...m,
    kind: 'lab',
    spec: (await exists(spec)) ? spec : null,
    tests,
    skips,
    thumb: (await exists(thumb)) ? thumb : null,
  });
}

const projects = [...lab];
for (const w of work) {
  projects.push({
    ...w,
    kind: w.category === 'Client Work' ? 'client' : 'classic',
    thumb: w.thumb && (await exists(w.thumb)) ? w.thumb : null,
  });
}

// Whole-suite size, as Playwright will report it: lab specs + the per-page smoke suite + the homepage suite.
const src = (f) => readFile(f, 'utf8');
const smokePerPage = countTests(await src('tests/site/lab-smoke.spec.ts'));
const home = await src('tests/site/home.spec.ts');
const labTests = lab.reduce((n, p) => n + p.tests, 0);
const labSkips = lab.reduce((n, p) => n + p.skips, 0);
const suite = {
  total: (labTests + smokePerPage * lab.length + countTests(home)) * PROJECTS_PER_RUN,
  skipped: labSkips + countSkips(home),
  lab: { total: labTests * PROJECTS_PER_RUN, skipped: labSkips },
};

const header = '// Generated by scripts/build-data.mjs; edit data/work.json or lab/_meta/*.json instead.\n';
await writeFile('data/projects.js',
  `${header}window.SUITE = ${JSON.stringify(suite)};\nwindow.PROJECTS = ${JSON.stringify(projects, null, 2)};\n`);

console.log(`Wrote ${projects.length} projects (${lab.length} lab pages). Suite: ${suite.total} tests, ${suite.skipped} skipped; lab ${suite.lab.total}.`);
